version: '2'
services:
  Server:
    build:
      context: ./server
      dockerfile: Dockerfile-alternate
    image: server:latest
    links:
      - ServiceCenter
#    ports:
#      - 3000:3000
  Client:
    build:
      context: ./client
      dockerfile: Dockerfile-alternate
    image: client:latest
    environment:
      - http_proxy=127.0.0.1:30101
    ports:
      - 3000:3000
    links:
      - Server
      - ServiceCenter
  MyPrometheus:
    build: ./prometheus
    image: my-prometheus:latest
    ports:
      - 9090:9090
    links:
      - Server
      - Client
  MyGrafana:
    image: grafana/grafana
    ports:
      - 9000:3000
  MyZipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  ServiceCenter:
    image: servicecomb/service-center
    ports:
      - 30100:30100
